version: '3'

services:
  frontend:
    build: ./frontend
    image: frontend
    volumes:
      - frontend:/app/

  backend:
    build: ./backend
    image: backend
    restart: always
    ports:
      - '8081:8081'
    volumes:
      - media-data:/app/media/
      - frontend:/frontend/
    depends_on:
      - db


  collectstatic:
    image: backend
    command: [ "python3", "manage.py", "collectstatic", "--noinput" ]
    volumes:
      - frontend:/app/staticfiles/
      - frontend:/frontend/
    depends_on:
      - frontend
      - backend

  migrate:
    image: backend
    command: [ "python3", "manage.py", "migrate"]
    depends_on:
      - backend

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
      POSTGRES_DB: burgers
    volumes:
      - postgres-data:/var/lib/postgresql

  web:
    image: nginx:stable
    volumes:
     - ./nginx.conf:/etc/nginx/conf.d/default.conf
     - frontend:/frontend/
     - media-data:/media/
    ports:
     - "80:80"


volumes:
  frontend:
  postgres-data:
  media-data: