# Generated by Django 4.2.20 on 2025-05-06 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geocoordapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='place',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(max_length=256, unique=True, verbose_name='Адрес'),
        ),
    ]
