# Generated by Django 4.2.20 on 2025-05-03 11:47

from django.db import migrations



def add_price_for_orders_items(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')

    for item in OrderItem.objects.all().iterator():
        item.price = item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_alter_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(add_price_for_orders_items),
    ]


