# Generated by Django 4.2.20 on 2025-05-03 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_order_called_at_order_delivered_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='regiastated_at',
            new_name='registered_at',
        ),
    ]
