# Generated by Django 4.2.20 on 2025-05-06 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_alter_order_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 5, 6, 21, 9, 43, 396669, tzinfo=datetime.timezone.utc), verbose_name='Зарегистрирован в'),
        ),
    ]
