# Generated by Django 4.2.20 on 2025-05-30 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0058_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('in_progress', 'В сборке'), ('in_delivery', 'В доставке'), ('completed', 'Выполнен')], db_index=True, default='accepted', max_length=30, verbose_name='Статус'),
        ),
    ]
