# Generated by Django 4.2.20 on 2025-05-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0061_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличными'), ('online', 'Электронно')], db_index=True, max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('in_progress', 'В сборке'), ('in_delivery', 'В доставке'), ('completed', 'Выполнен')], db_index=True, default='accepted', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=200, verbose_name='описание'),
        ),
    ]
