#!/bin/bash
set -Eeuo pipefail
cd /opt/star-burger
git pull
source venv/bin/activate
pip install -r requirements.txt
npm ci --dev
./node_modules/.bin/parcel build bundles-src/index.js --dist-dir bundles --public-url="./"
python manage.py collectstatic --noinput
python manage.py migrate
systemctl restart star_burger.service
systemctl reload nginx.service
echo "Сайт успешно обновился!"
http POST https://api.rollbar.com/api/1/deploy \
  X-Rollbar-Access-Token:06c55812f8d94a198c90691ceb97c9939d5e37305acb6f1a5a7404b34039a9f380bd2eb6c808c8cf5e3767b4779f77ae \
  accept:application/json \
  content-type:application/json \
  environment=production \
  revision=$(git rev-parse HEAD)
