# Generated by Django 4.2.20 on 2025-05-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('accepted', 'Принят'), ('in_progress', 'В сборке'), ('in_delivery', 'В доставке'), ('completed', 'Выполнен')], db_index=True, default='accepted', max_length=20, verbose_name='Статус'),
        ),
    ]
