# Generated by Django 4.2.20 on 2025-05-03 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0050_rename_regiastated_at_order_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 5, 3, 17, 17, 20, 753621, tzinfo=datetime.timezone.utc), verbose_name='Зарегистрирован в'),
        ),
    ]
