# Generated by Django 4.2.20 on 2025-05-06 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_order_restaurant_alter_order_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2025, 5, 6, 19, 32, 57, 761652, tzinfo=datetime.timezone.utc), verbose_name='Зарегистрирован в'),
        ),
    ]
