# Generated by Django 4.2.20 on 2025-05-13 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_alter_order_registered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='registered_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Зарегистрирован в'),
        ),
    ]
