# Generated by Django 4.2.20 on 2025-05-06 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=256, verbose_name='Адрес')),
                ('lon', models.FloatField(verbose_name='Долгота')),
                ('lat', models.FloatField(verbose_name='Широта')),
                ('request', models.TimeField(auto_now=True, verbose_name='Запрос к API')),
            ],
            options={
                'verbose_name': 'место',
                'verbose_name_plural': 'места',
                'unique_together': {('lon', 'lat')},
            },
        ),
    ]
